config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "refile", controller: 'items', action: 'refile'
  post "search_refile_errors", controller: 'items', action: 'search_refile_errors'
  get "transfer_metadata", controller: 'items', action: 'transfer_metadata'
  get "update_metadata", controller: 'items', action: 'update_metadata'
  get "authenticate", controller: 'oauth', action: 'authenticate'
  get "callback", controller: 'oauth', action: 'callback'
  get "log_out", controller: 'oauth', action: 'log_out'
  post "send_metadata", controller: 'items', action: 'send_metadata'
  post "send_transfer_metadata", controller: 'items', action: 'send_transfer_metadata'
  post "send_refile_request", controller: 'items', action: 'send_refile_request'
  get "error", controller: 'error', action: 'error'
  root controller: 'items', :action => 'update_metadata'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>SCSBuster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="scsbuster">
      <header class="app-header">
        <div class="nypl-full-width-wrapper">
          <h1 class="title"><%= link_to 'SCSBuster', root_url, { style: "text-decoration: none;" } %></h1>
        </div>
      </header>
      <div class="nypl-full-width-wrapper app-content">
        <div class="nypl-row">
          <% unless controller.controller_name == "error" %>
            <nav class="nypl-column-one-quarter sidebar-navigation" id="sidebar-navigation">
              <ul>
                <li><%= link_to "Update Metadata", update_metadata_path %></li>
                <li><%= link_to "Transfer Barcode & Update Metadata", transfer_metadata_path %></li>
                <li><%= link_to "Refile", refile_path %></li>
                <li><%= link_to "Log Out", log_out_path %></li>
              </ul>
            </nav>
          <% end %>
          <main class="nypl-column-three-quarters">
            <%= yield %>
          </main>
        </div>
      </div>
    </div>
  </body>
</html>